services:
  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: todoapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api:
    build: ./TodoApi
    container_name: todo-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123.
      POSTGRES_DB: todoapp
    restart: always

  frontend:
    build: ./todo-frontend
    container_name: todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      VITE_API_URL: "http://api:8080"  # Lokal test için dış port
    restart: always

volumes:
  postgres_data:
